name: M2 Integration Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration-tests:
    name: Integration Tests - PHP ${{ matrix.php }} / Magento ${{ matrix.magento }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php: '8.1'
            magento: '2.4.6'
          - php: '8.2'
            magento: '2.4.6'
          - php: '8.2'
            magento: '2.4.7'
          - php: '8.3'
            magento: '2.4.7'
          - php: '8.3'
            magento: '2.4.8'
          - php: '8.4'
            magento: '2.4.8'

    steps:
      - uses: actions/checkout@v4

      # PHP 8.1
      - name: M2 Integration Tests (PHP 8.1 / Magento ${{ matrix.magento }})
        if: matrix.php == '8.1'
        uses: extdn/github-actions-m2/magento-integration-tests/8.1@master
        with:
          module_name: Buckaroo_Magento2
          composer_name: buckaroo/magento2
          ce_version: ${{ matrix.magento }}

      # PHP 8.2
      - name: M2 Integration Tests (PHP 8.2 / Magento ${{ matrix.magento }})
        if: matrix.php == '8.2'
        uses: extdn/github-actions-m2/magento-integration-tests/8.2@master
        with:
          module_name: Buckaroo_Magento2
          composer_name: buckaroo/magento2
          ce_version: ${{ matrix.magento }}

      # PHP 8.3
      - name: M2 Integration Tests (PHP 8.3 / Magento ${{ matrix.magento }})
        if: matrix.php == '8.3'
        uses: extdn/github-actions-m2/magento-integration-tests/8.3@master
        with:
          module_name: Buckaroo_Magento2
          composer_name: buckaroo/magento2
          ce_version: ${{ matrix.magento }}

      # PHP 8.4
      - name: M2 Integration Tests (PHP 8.4 / Magento ${{ matrix.magento }})
        if: matrix.php == '8.4'
        uses: extdn/github-actions-m2/magento-integration-tests/8.4@master
        with:
          module_name: Buckaroo_Magento2
          composer_name: buckaroo/magento2
          ce_version: ${{ matrix.magento }}
